name: Deploy website to AWS S3 and Invalidates CloudFront Cache

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - uses: byrro/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'byrro.dev'
        AWS_CLOUDFRONT_DISTRIBUTION_ID: 'E2E70YGSXIPJRD'
        AWS_ACCESS_KEY_ID: 'AKIASSR55UJUPI2QOLY5'
        AWS_SECRET_ACCESS_KEY: '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'
        CLOUDFRONT_INVALIDATION_PATH: '/*'
        AWS_REGION: 'us-east-1'
        SOURCE_DIR: 'src'
